### ISSUE TITLE
Mass conversion not working

### ISSUE THREAD

**Issue by CJ3625** [ck2plus/CleanSlate#105]
While playing tribal unreformed germanic pagan and using the targeted decision to request a mass conversion,, even if the tooltip says the sponsor will accept no event fires to do the actual mass conversion, tried using the targeted decision then changing character to the sponsor to see if the event is visible to no avail

**Comment by CJ3625** [comment]
Found the issue:
In HF_baptism_events, event HF.20000:
`					custom_tooltip = {
			text = accept_baptism_request

			hidden_effect = {
				set_character_flag = flag_sponsoring_baptism
				FROMFROM = { save_event_target_as = converting_king } <this line was missing so the event_target:converting_king didnt have a character to call upon, i think
				save_event_target_as = sponsoring_king

				event_target:converting_king = {
					set_character_flag = flag_converting_baptism

					letter_event = {
						id = HF.20002
						days = 5
						random = 5
					}
				}
			}
		}
`

**Comment by Whizzer** [comment]
Thanks for finding this. I fixed it in the decision calling this event, but you were right about the cause.
