### ISSUE TITLE
Obsoleted has_disease_trigger is still being used

### ISSUE THREAD

**Issue by Aerotinge** [ck2plus/CleanSlate#109]
```has_disease_trigger``` had been removed in 0c968bbc, but still in
https://github.com/ck2plus/CleanSlate/blob/38d02cbd4335e80c88a3bfc727d04b0f4be9628e/CleanSlate/events/HF_warrior_lodge_flavor_events.txt#L1740

**Comment by Whizzer** [comment]
Thanks!
