### ISSUE TITLE
Everyone hates Cats

### ISSUE THREAD

**Issue by Aerotinge** [ck2plus/CleanSlate#110]
https://github.com/ck2plus/CleanSlate/blob/38d02cbd4335e80c88a3bfc727d04b0f4be9628e/CleanSlate/common/traits/00_animals.txt#L27
Why -200 instead of vanilla -20? This is equivalent to everyone treating the cat (and Glitterhoof) as a bitter rival.
I think it's overcorrection.

**Comment by Whizzer** [comment]
Thanks again!
