### ISSUE TITLE
absolute cog for city vassals

### ISSUE THREAD

**Issue by zzcmeiou** [ck2plus/CleanSlate#114]
Seems like raising a new vassal for a city still defaults to agnatic open elective, shouldnt it be true cog?

``` 
					trigger_if = {
						limit = { is_republic = yes }

						has_dlc = "Conclave"
						is_patrician = yes

						trigger_if = {
							limit = { independent = no }

							defacto_liege_title = {
								OR = {
									has_law = true_cognatic_succession
									has_law = cognatic_succession
									has_law = enatic_cognatic_succession
								}
							}
						}
					}
```

I think this block only applies to patrician republics, should there be another for plain city republic? Not sure why the insert code function isnt working right for me.

**Comment by Whizzer** [comment]
That block is there for patricians so that merchant republic elections don't break.
In general, CleanSlate seeks to keep things identical to vanilla, so unless we introduced a difference, I see no reason to change things.
