### ISSUE TITLE
Cannot introduce heir to realm even when conditions are met

### ISSUE THREAD

**Issue by Adminusart** [ck2plus/CleanSlate#120]
![20220215185820_1](https://user-images.githubusercontent.com/22868305/154131431-c0f08d37-3fac-4e78-bf7d-631d3bb8eadc.jpg)
![20220215185826_1](https://user-images.githubusercontent.com/22868305/154131463-9e594e0d-c7e5-46a9-a97a-1fd1fce2dc84.jpg)
 Not visible on the screen (he is 14)

**Comment by SuccinctScrivener** [comment]
Thank you for making these bug reports; they are very helpful. This issue will be fixed in the next release.
