### ISSUE TITLE
Got euneched and lost my seduction focus, but the game still thinks i am trying to seduce someone even if im an eunuch (WAD?)

### ISSUE THREAD

**Issue by Adminusart** [ck2plus/CleanSlate#121]
![20220215222724_1](https://user-images.githubusercontent.com/22868305/154152617-f2360900-e9c1-4e03-a32b-f66e09279e9b.jpg)
![20220215222714_1](https://user-images.githubusercontent.com/22868305/154152634-3c20e33b-6eef-4580-893a-ce076d09434b.jpg)
![20220215222719_1](https://user-images.githubusercontent.com/22868305/154152652-17254709-c02d-4971-8448-6624772ce048.jpg)

**Comment by Adminusart** [comment]
I'm also a lustful eunuch, does that make any sense? I mean it may have but i don't really know

**Comment by SuccinctScrivener** [comment]
This shouldn't be an issue as the next time the seduction tombola tries to fire (20-40 days after it last fired ), it will see that you no longer have the seduction focus and the event chain will terminate and opinion modifiers and so forth will be cleaned up.

I imagine a lustful eunuch is a particularly frustrated one.
