### ISSUE TITLE
I can usurp my vassal's title (WAD?)

### ISSUE THREAD

**Issue by Adminusart** [ck2plus/CleanSlate#122]
![20220215222818_1](https://user-images.githubusercontent.com/22868305/154152827-7a6f30c2-e9a8-4e3d-ab06-632dd12104d3.jpg)
![20220215222832_1](https://user-images.githubusercontent.com/22868305/154152847-29ceaa48-e5f2-4d57-8f33-4de67e30dbe5.jpg)

**Comment by SuccinctScrivener** [comment]
This a vanilla feature. You can usurp a vassal's duchy or kingdom title if you have a claim on it.
