### ISSUE TITLE
Localisation error on event MnM.4428 (Monastic penance success)

### ISSUE THREAD

**Issue by wtrmute** [ck2plus/CleanSlate#135]
Hello,

I am playing with 1.0Beta4 and have noticed that the localisation button for event `MnM.4428` does not write out the title for the society leader. Looking up the event by enabling `charinfo` and Ctrl-right-clicking on the button, I can see that the relevant key is `EVTOPTA_MNM_4428`, which happens to be located in `/CleanSlate/localisation/13_mnm_monastic_orders_events.csv` and has the following English form:

> EVTOPTA_MNM_4428;You honor me, [Society.GrandMaster.GetSocietyRank];

Note that the event immediately below it, which is the failure event for the same decision, has a different way of picking the leader's title:

> EVTOPTA_MNM_4429;I have failed you, [monastic_leader.GetSocietyRank].;

I am not sure whether it would work to simply replace `Society.GrandMaster` with `monastic_leader`, but it would seem to work at least in this case, as the event mentions `event_target:monastic_leader`. In any case, I think `Society.GrandMaster` would probably need to be replaced everywhere?

Thanks for the attention.

**Comment by Whizzer** [comment]
You're correct in your analysis every step of the way. Fortunately `Society.GrandMaster` isn't found anywhere else. Another fix would have been `Root.Society.GrandMaster`, but using the provided event target is preferred, and more consistent, as you already found out.
Thanks for bringing this to our attention!
