### ISSUE TITLE
Malformed has_cultural_titular_requirements scripted_trigger

### ISSUE THREAD

**Issue by Aerotinge** [ck2plus/CleanSlate#138]
https://github.com/ck2plus/CleanSlate/blob/0c968bbc04aa11d671babf10413e1c1a6c4528f7/CleanSlate/common/scripted_triggers/00_title_triggers.txt#L40-L45
I'm not sure about this. Shall it be like?
```
has_cultural_titular_requirements = {
	trigger_if = {
		limit = { ai = yes }
		culture = FROM
	}
}
```

**Comment by Whizzer** [comment]
Yes, of course it should be as you suggest. Fix incoming.
