### ISSUE TITLE
Incorrect notification for skill taught by chinese strategist

### ISSUE THREAD

**Issue by kwkam** [ck2plus/CleanSlate#146]
Always "Way of Dragon" because `commander_student` is not yet defined before L1985. Probably also no protrait.
https://github.com/ck2plus/CleanSlate/blob/7791c2618f89c847ad1d2844f49140ff493202d4/CleanSlate/events/jd_grace_decision_events.txt#L1904-L1986
Since #45 merged some chain of events into one, there maybe more this kind of issue.

**Comment by kwkam** [comment]
Took some time to test this, when I commented `notification = yes`, the dialog displays correct information.
Perhaps this event should also show dialog, such as the Marshal improves commander event.

**Comment by SuccinctScrivener** [comment]
Resolved with 2bb4801
