### ISSUE TITLE
Reformed bon religion is a heresy religion by default

### ISSUE THREAD

**Issue by Aerotinge** [ck2plus/CleanSlate#179]
![203770_20231029164434_1](https://github.com/ck2plus/CleanSlate/assets/6275647/6d1b08c3-322f-4eaa-812d-6282223eb8d7)
After the reform, bon_pagan_reformed using heresy_icon instead of the normal one.
However it is not really heretic, using `is_heretic = yes` on it will return false.
I also tried reformed Zun and Hellenic, both of them are working normally.
It's uncertain that this problem has been occurring since which version.

**Comment by Aerotinge** [comment]
![圖片](https://github.com/ck2plus/CleanSlate/assets/6275647/5a4072b7-36a0-4c2e-85bf-5aad317d9a42)
However, If I delete the reordered religion_icon_strip graphics that with CleanSlate, it does render icon correctly(the 58th frame of vanilla graphic is exactly reformed_hellenic).

**Comment by SuccinctScrivener** [comment]
Resolved with 425e161
