### ISSUE TITLE
Can't use Alexander Bloodline casus belli

### ISSUE THREAD

**Issue by xdpfxdpf** [ck2plus/CleanSlate#189]
There is no Invasion casus belli available. Please fix it asap

**Comment by schwarherz** [comment]
Going to need more information than that. Are you using other mods? What is the expected behavior? What are the steps to reproduce the issue? Do you have a save file we can test with?

**Comment by Whizzer** [comment]
Works just fine on my end. Note that CleanSlate requires most bloodlines be active for them to work.
