### ISSUE TITLE
Drill Troops tooltip is missing for +10% Movement Speed

### ISSUE THREAD

**Issue by intyrist1993** [ck2plus/CleanSlate#199]
![image](https://github.com/ck2plus/CleanSlate/assets/99834662/48055dd4-b84b-45eb-a24f-b2c4fb41cb65)
Drill Troops tooltip is missing for +10% Movement Speed

The Warrior Philosopher bloodline give Drill Troops option //right click on character portrait

**Comment by Whizzer** [comment]
This is unfortunately hardcoded, but I've made a note in my long list of bugs that can only be fixed with access to the game's source code.
