### ISSUE TITLE
Genoa getting too much money

### ISSUE THREAD

**Issue by CJ3625** [ck2plus/CleanSlate#213]
Playing last branch, at start date 867 noticed Genoa had 9.8 million gold, got suspicious, started new game and entered observe mode after selecting genoa to see what was up i noticed Genoa changing goverment to merchant republic and normal republic in a loop after being granted the duchy level title by Italian King and its gold changing drastically even if the income is not registered on the title ledger

![imagen](https://github.com/user-attachments/assets/3558d68b-844d-4c55-806c-585c6a601a26)
![imagen](https://github.com/user-attachments/assets/d6b3f5dc-c5f7-40fa-b4d0-9cb00852ab1d)
![imagen](https://github.com/user-attachments/assets/e34e83de-53bb-4ce1-8613-563e6a9260a6)

it's changing at 500 gold per day

**Comment by CJ3625** [comment]
Also happens with Dalmatia, interestingly Venice and Amalfi don't have this issue

**Comment by schwarherz** [comment]
Seems when I last edited the Merchant Republic requirements I forgot to account for vassal MRs. Investigating for a fix.
