### ISSUE TITLE
Minor bug when forming Habsburg

### ISSUE THREAD

**Issue by bladesmoss** [ck2plus/CleanSlate#214]
I started in 769 as the count of Basel. 
Saved up gold and couldn't form Von Habsburg. 
Captured some nearby counties and the option was there. 
Formed. 
The game things the castle is in Saarbrucken and Basel at the same time. 

The castle is visually in one of the holding slots for Saarbrucken, but when I view the actually barony tier title it centers on Basel and highlights the county.  I granted Saarbrucken to someone just to double check and it doesn't outline any holdings in that area for me, despite the castle being up there. 

Not sure what other info you may need. Screenshots attached. 

![image](https://github.com/user-attachments/assets/c6b2fb43-15fd-430d-a485-b85f1e3ad8e9)
![image](https://github.com/user-attachments/assets/6ce44984-2e75-4f14-a55e-ca8695c5063c)

**Comment by schwarherz** [comment]
Issue seems to have occurred when replacing the province number references with county references in CleanSlate as well as updating the county names and renumbering the provinces. In Vanilla the relevant counties are Province 242 `c_aargau` and Province 1986 `c_saargau`. In CleanSlate these have been updated to Province 345 `c_basel` and Province 242 `c_saarbrucken`, respectively. `b_habsburg` is still properly in `c_basel` in the `landed_titles` but the decision to build it references `c_saarbrucken` instead.

I'll push a fix momentarily, but if you want to fix it on your own end without re-downloading just change lines 558 and 561 of `LT_936_decisions.txt` from `c_saarbrucken` to `c_basel`
