### ISSUE TITLE
Can't find a way to create this bloodline: event_religion_aggressive_bloodline_01

### ISSUE THREAD

**Issue by Saint-in-Chief** [ck2plus/CleanSlate#36]
The only place I see it mentioned is in, events\HF_bloodline_events.txt, but events to create both religious bloodlines are completely commented out, and the events that should lead to them do it instead to the creation of event_family_bloodline_01, I think. There are possibly more events that lead to the incorrect bloodline, though I haven't fully checked.

**Comment by schwarherz** [comment]
This issue is two months old. Now that we're entering the cleanup stage, it might be worth checking to see if this is still the case. @ck2plus/teamclean could you please investigate?
