### ISSUE TITLE
if/else_if instead of random_list in china_war_modify_variables_by_century_effect. Is there a good reason?

### ISSUE THREAD

**Issue by Aerotinge** [ck2plus/CleanSlate#54]
https://github.com/ck2plus/CleanSlate/blob/6b4eb96fa19b57914928dd4102b682f5fdc021c8/CleanSlate/common/scripted_effects/00_china_effects.txt#L973-L992
By using if/else_if, the effect lost randomness and only the first valid condition fires.
I guess it's not the way this effect should be.

**Comment by Whizzer** [comment]
I don't see how this is any different from vanilla's random_list, which is fully gated to only allow one option to ever occur.

**Comment by Aerotinge** [comment]
Say, if it's year = 1300 now.
Vanilla's random_list still allow it pick "nothing fires" effect even (with a small chance), while if/else_if only allow the first effect to be picked.
