### ISSUE TITLE
model files defined in DLC should not be in base game

### ISSUE THREAD

**Issue by Aerotinge** [ck2plus/CleanSlate#55]
I have frequently CTD with CleanSlate, it turn out to be some dlc related files was moved and loaded in the base game with Cleanslate.
For people who did not own proper DLCs or who simply hate it and not enable it, they could get CTD with something like this in error.log.
`[virtualfilesystem.cpp:753]: Could not open file: gfx/models/arabian_ship.xac, error: not found`
Graphic files modding are a bit tricky here, and separating Cleanslate into correspoding content pack patch is the Paradox dumb way...

Maybe an Installer?...(facepalm

**Comment by schwarherz** [comment]
Can you give specific examples of which dlc files were mistakenly included? We tried to remove them all but may have missed some.

**Comment by Aerotinge** [comment]
My dlcs enabled in settings.txt
`
last_dlcs=
{
	dlc/dlc069.dlc dlc/dlc036.dlc dlc/dlc072.dlc dlc/dlc011.dlc dlc/dlc066.dlc dlc/dlc022.dlc dlc/dlc078.dlc dlc/dlc050.dlc dlc/dlc062.dlc dlc/dlc054.dlc 
}
`

**Comment by Aerotinge** [comment]
It turn out to be interface/Ships_avatars.gfx that causes CTD.
This file defined some actorfile that is not in the base game, and CK2 crashed if required DLC is not enable or not exists.

I recommend removing it, since neither a script stylization nor cleanup should create more bugs/errors/warnings.
