### ISSUE TITLE
Provinces with inconsistent terrain comparing to vanilla

### ISSUE THREAD

**Issue by Aerotinge** [ck2plus/CleanSlate#65]
I found there're many provinces have different terrain comparing to vanilla.
Using following script for testing
```
any_province = {
	limit = {
		terrain = arctic
	}
	log = "[This.County.GetName] is arctic terrain"
}
```

# Result(Vanilla)

49 Lines/Provinces, alphabetized
<details>
<summary>game.log</summary>
<pre>
[effectimplementation.cpp:18398]: EVENT [769.1.1]:--- is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Austisland is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Bjarmia is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Bolshoy Yugan is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Dvina is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Hlynov is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Illyinsk is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Indiga is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Izhma is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Kanin is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Keltma is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Khantia is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Khlynov is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Kola is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Kolguyev is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Kolva is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Koshma is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Kudymkar is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Kuloy is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Mansia is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Mezen is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Narim is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Norðland is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Onega Peninsula is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Perm is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Pil'va is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Pinega is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Sedyu is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Severnaya is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Snopa is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Suðurland is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Syrj is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Tavda is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Tobysh is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Tom is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Tsilma is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Ugra is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Ural is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Vashka is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Vasyugan is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Vel is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Veliky Ustug is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Velsk is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Vestisland is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Vishera is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Vychegda is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Vym is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Yamalia is arctic terrain
[effectimplementation.cpp:18398]: EVENT [769.1.1]:Zavarot is arctic terrain
</pre>
</details>

# Result(CleanSlate)

61 Lines/Provinces, alphabetized
<details>
<summary>game.log</summary>
<pre>
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:--- is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Austisland is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Bjarmia is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Bolshoy Yugan is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Borovichi is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Calarasi is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Dvina is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Hlynov is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Illyinsk is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Izhma is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Kanin is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Karachev is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Keltma is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Khantia is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Khlynov is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Kola is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Kolguyev is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Kolva is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Koshma is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Kozelsk is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Kromy is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Kudymkar is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Kuloy is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Kursk is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Mansia is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Mezen is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Narim is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Norðurland is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Novosil is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Onega Peninsula is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Perm is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Pil'va is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Pinega is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Priluk is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Rylsk is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Sedyu is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Severnaya is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Snopa is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Soyma is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Suðurland is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Syrj is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Tavda is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Tikhvine is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Tobysh is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Tom is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Tsilma is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Ugra is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Ural is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Vashka is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Vasyugan is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Vel is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Veliky Ustug is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Velsk is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Vestisland is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Vishera is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Vorotynsk is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Vychegda is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Vym is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Yamalia is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Zavarot is arctic terrain
[effectimplementation.cpp:18398]: EVENT [1066.9.15]:Zvenyhorod is arctic terrain
</pre>
</details>
<br></br>
I think some terrain in province was mistaken. It's not intentionally, right?

**Comment by Whizzer** [comment]
This was not intended, no. I must have been a bit too careless when re-organising the map a while ago.
