### ISSUE TITLE
landless title attribute not save into a save game, maintenance events needed.

### ISSUE THREAD

**Issue by Aerotinge** [ck2plus/CleanSlate#66]
This is an old vanilla bug. In CK2 if a title was `set_title_landless` by script in a game, it does not stay landless after you loaded a savefile, which the title is not in landless status. 
In other words, title mapping of CK2 is not clean up when resign and load another save.<br>
Take `e_mongol_empire` as example, fire event 60500, Genghis could start invading eastern edge of map in most of time, with a `e_mongol_empire` title set as landless to allow it being there till Genghis holds at least one province, and a flag `temporary_landless_title` for triggering an event to set the title back to normal status.<br>
However if I save a game at first time and quit to the desktop, restart and load the savegame. The game now take `e_mongol_empire` as a normal title since any title status is imported from /landed_titles and savefile doesn't containing such a meta data.
The poor Genghis will lost his title due to unland and his war goes invalid.

I use an on_start hook event to check if this is a savegame or not, and filter any_title with temporary_landless_title flag and then manually set it up to make sure it working.
I'm not sure what style of fix you tend to do, so I post an issue first instead a pr.

**Comment by Whizzer** [comment]
Sadly, I can confirm what you wrote here. Thanks for informing us!
