### ISSUE TITLE
tribal_organization_0 added when decrease tribal organization

### ISSUE THREAD

**Issue by Aerotinge** [ck2plus/CleanSlate#67]
A rather weird bug. I attached screenshots for better understanding.
# Before
![圖片](https://user-images.githubusercontent.com/6275647/125901423-1c600f0c-0a2b-414c-ad16-7dd1e9a3d0c3.png)
# After Low tribal organization applied
![圖片](https://user-images.githubusercontent.com/6275647/125901518-c63cb422-ff1e-4dde-9f37-58b871fedc90.png)
(Please ignore in-game date, I did not take screenshots in time sequence.)
<br>
tribal_organization_0 was added. This bug won't be triggered if I did not have centralization_2 at the beginning.
It seems that a fallback mis-triggered when `add_law = centralization_1` fired in the pass_effect block.
I tried to debug but I'm not that good at law modding. Sorry I can't help more.

A dirty fix is to place revoke_law sequence after if block, in case of the quirk is hard coded.

**Comment by Aerotinge** [comment]
UPDATE: It seems that this kind of bug also happened on investiture_law_* and maybe gender_laws. But I can't reproduce it this time.

**Comment by schwarherz** [comment]
I believe this is vanilla behavior. I seem to recall wondering why paradox did that when I last worked on the laws, but I'll wait for @Whizzer to comment.
