### ISSUE TITLE
Paper of Vestisland(Iceland) has feudal_government in 769 pre-game character selection screen.

### ISSUE THREAD

**Issue by Aerotinge** [ck2plus/CleanSlate#68]
769 bm, if a player picks up house Papar and press Play, he gets gameover right now.
![圖片](https://user-images.githubusercontent.com/6275647/126032391-bab05c61-786c-4568-b117-0a3cea505de9.png)

Leave CleanSlate aside, though I think 769 iceland is history inaccurate (sigh
But CK2 engine did not like wasteland tricks I used in [Iceland's settlement](https://steamcommunity.com/sharedfiles/filedetails/?id=1836687243) mod, it spamming a shitty ton of warnning in log.

769 bm is horrible...

**Comment by schwarherz** [comment]
Fixed in dev
