### ISSUE TITLE
temple holding granted by a feudal/tribal holder not switching theocracy

### ISSUE THREAD

**Issue by Aerotinge** [ck2plus/CleanSlate#77]
Step to reproduce:

1. Play any catholic ruler, revoke a bishop.
2. Grant the newly revoked temple to a courtier.
3. He's a baron now.

It seems the suffering is not over yet. But thankfully that your old scripts works here this time.
```
theocratic_group_allow_trigger = {
	trigger_if = {
		limit = { has_game_started = yes }

-		is_theocracy = yes
+		is_feudal = no
+		is_tribal = no
+		is_nomadic = no
+		is_republic = no
	}
}
```
Not comprehensively tested, there might be reason you changed it. but I don't know.

**Comment by schwarherz** [comment]
When I got the first report of this over on the Ck2Plus repository I suspected this might be the culprit. I'll get the change in as soon as I have the time
