### ISSUE TITLE
Special crown portrait not displayed, HF.20406 bad trigger

### ISSUE THREAD

**Issue by Aerotinge** [ck2plus/CleanSlate#91]
CleanSlate bug
- portrait p18, p19 not displayed. Using vanilla scripts fixes the bug, but I guess you have some idea about it.

- HF.20406 only check has_landed_title and then add_trait, ignoring whether the artifact is actually held and is active or not.
That said, HF.20415 is not properly merged into HF.20406.
https://github.com/ck2plus/CleanSlate/blob/553d80226d170c0210e165e0d1ab73bc2cfe174f/CleanSlate/events/HF_coronation_events.txt#L15038-L15055

**Comment by Whizzer** [comment]
This should be all of it. I decided I'd deal with the second part this way, so you wouldn't have to open a new pull request, aside from some changes I made.

**Comment by Aerotinge** [comment]
When I write HF.20407, I did not take `k_italy` and `iron_crown_of_lombardy` into consideration.
I guess you would like to include them also.
But it brings up another question. If HRE emperor want to make a vassal of him king/viceroy of italy. 
Who owns `iron_crown_of_lombardy`?

**Comment by Whizzer** [comment]
As for your last question, I don't think AI wants anything. A player could manually grant the crown.

**Comment by Aerotinge** [comment]
OK. I guess you might also need to patch HF.20407 the same way as HF.20414 did. So it goes with the new HR Kaiser when FROMFROM being overthrown.
