### ISSUE TITLE
failed to generate correct tooltip for convert_religion_failsafe_effect

### ISSUE THREAD

**Issue by Aerotinge** [ck2plus/CleanSlate#97]
https://github.com/ck2plus/CleanSlate/blob/52a42ea43704c94a0264e2a97468d740fc6fe1f5/CleanSlate/decisions/mnm_secret_religious_societies_decisions.txt#L1763-L1767
When `convert_religion_failsafe_effect` was called in `secret_religions_personally_adopt_secret_religion`, the tooltip returns `noreligion` on this occasion.
The decision effect itself is actually working fine, though.
![圖片](https://user-images.githubusercontent.com/6275647/137592821-df28168c-b069-4388-8ba6-eb76f4bb6d64.png)
It's more likely a vanilla glitch but unfortunately triggered in CleanSlate.

**Comment by Whizzer** [comment]
Fixed by [https://github.com/ck2plus/CleanSlate/commit/e798d6b931cb13adecfdce616396fb604d2a50b0](url)
